### ISSUE TITLE
Doesn't work on IE

### ISSUE THREAD

**Issue by flomader** [Microsoft/PowerBI-Angular#3] opened 2016-05-20 07:03 UTC
Embedded Report fails on Windows 10 + IE11 because of the following JavaScript Error:
**"TypeError: Unable to get property 'toLowerCase' of undefined or null reference"**

Works on Windows 10 + Edge or Chrome.

Can be tested here:
http://pbiembedded.azurewebsites.net/

**Comment by mattmazzola** [comment] 2016-05-20 17:18
Yes, I confirmed this. It looks like IE11 doesn't support the `function.name` property.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name

I think we can work around this by explicitly setting the value to a string instead of relying on the javascript engine to do this for us.   Browsers should implement this going forward since it will be part of ES6

**Closed** 2016-05-20 18:57 UTC
Labels: bug
